Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/group/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &wdra
        Name: wdraMSP
        ID: wdraMSP
        MSPDir: crypto-config/peerOrganizations/wdra.group/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('wdraMSP.admin', 'wdraMSP.peer', 'wdraMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('wdraMSP.admin', 'wdraMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('wdraMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('wdraMSP.peer')"
        AnchorPeers:
            - Host: peer1.wdra.group
              Port: 7051

    - &pvcs
        Name: pvcsMSP
        ID: pvcsMSP
        MSPDir: crypto-config/peerOrganizations/pvcs.group/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('pvcsMSP.admin', 'pvcsMSP.peer', 'pvcsMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('pvcsMSP.admin', 'pvcsMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('pvcsMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('pvcsMSP.peer')"

        AnchorPeers:
            - Host: peer1.pvcs.group
              Port: 9051

    - &clm
        Name: clmMSP
        ID: clmMSP
        MSPDir: crypto-config/peerOrganizations/clm.group/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('clmMSP.admin', 'clmMSP.peer', 'clmMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('clmMSP.admin', 'clmMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('clmMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('clmMSP.peer')"

        AnchorPeers:
            - Host: peer1.clm.group
              Port: 11051

    - &ins
        Name: insMSP
        ID: insMSP
        MSPDir: crypto-config/peerOrganizations/ins.group/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('insMSP.admin', 'insMSP.peer', 'insMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('insMSP.admin', 'insMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('insMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('insMSP.peer')"

        AnchorPeers:
            - Host: peer1.ins.group
              Port: 13051

    - &bank
        Name: bankMSP
        ID: bankMSP
        MSPDir: crypto-config/peerOrganizations/bank.group/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('bankMSP.admin', 'bankMSP.peer', 'bankMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('bankMSP.admin', 'bankMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('bankMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('bankMSP.peer')"

        AnchorPeers:
            - Host: peer1.bank.group
              Port: 14051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer1.group:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    FourOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *wdra
                - *pvcs
                - *clm
                - *ins
                  #- *bank
            Capabilities:
                <<: *ApplicationCapabilities

    Raft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer1.group
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer1.group/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer1.group/tls/server.crt
                - Host: orderer2.group
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer2.group/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer2.group/tls/server.crt
                - Host: orderer3.group
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer3.group/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer3.group/tls/server.crt
                - Host: orderer4.group
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer4.group/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer4.group/tls/server.crt
                - Host: orderer5.group
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer5.group/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/group/orderers/orderer5.group/tls/server.crt
            Addresses:
                - orderer1.group:7050
                - orderer2.group:7050
                - orderer3.group:7050
                - orderer4.group:7050
                - orderer5.group:7050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *wdra
                - *pvcs
                - *clm
                - *ins
                  #  - *bank
