OrdererOrgs:

  - Name: Orderer
    Domain: group
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 5


PeerOrgs:
  - Name: wdra
    Domain: wdra.group
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 1
    Users:
      Start: 1
      Count: 1

  - Name: pvcs
    Domain: pvcs.group
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 1
    Users:
      Start: 1
      Count: 1


  - Name: clm
    Domain: clm.group
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 1
    Users:
      Count: 1

  - Name: ins
    Domain: ins.group
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 1
    Users:
      Start: 1
      Count: 1

  - Name: bank
    Domain: bank.group
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 1
    Users:
      Start: 1
      Count: 1
