version: '2'

volumes:
  orderer1.talentsprint:
  orderer2.talentsprint:
  orderer3.talentsprint:
  orderer4.talentsprint:
  orderer5.talentsprint:
  peer1.mypeer1.talentsprint:
  peer2.mypeer1.talentsprint:
  peer1.mypeer2.talentsprint:
  peer2.mypeer2.talentsprint:
  peer1.mypeer3.talentsprint:
  peer2.mypeer3.talentsprint:
  peer1.mypeer4.talentsprint:
  peer2.mypeer4.talentsprint:

networks:
  byfn:

services:
  orderer1.talentsprint:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer1.talentsprint
    
    
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer1.talentsprint/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer1.talentsprint/tls/:/var/hyperledger/orderer/tls
        - orderer1.talentsprint:/var/hyperledger/production/orderer
    ports:
    - 7050:7050

  orderer2.talentsprint:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer2.talentsprint
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer2.talentsprint/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer2.talentsprint/tls/:/var/hyperledger/orderer/tls
        - orderer2.talentsprint:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.talentsprint:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer3.talentsprint
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer3.talentsprint/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer3.talentsprint/tls/:/var/hyperledger/orderer/tls
        - orderer3.talentsprint:/var/hyperledger/production/orderer
    ports:
    - 9050:7050


  orderer4.talentsprint:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer4.talentsprint
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer4.talentsprint/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer4.talentsprint/tls/:/var/hyperledger/orderer/tls
        - orderer4.talentsprint:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.talentsprint:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer5.talentsprint
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer5.talentsprint/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/talentsprint/orderers/orderer5.talentsprint/tls/:/var/hyperledger/orderer/tls
        - orderer5.talentsprint:/var/hyperledger/production/orderer
    ports:
    - 11050:7050


  peer1.mypeer1.talentsprint:
    container_name: peer1.mypeer1.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mypeer1.talentsprint
      - CORE_PEER_ADDRESS=peer1.mypeer1.talentsprint:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.mypeer1.talentsprint:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.mypeer1.talentsprint:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mypeer1.talentsprint:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
     # - FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgZ+60xQvTq/z6F/ZbQrFdf52ALHHJ2U9z/ixk2wENH3ShRANCAARLHHokC1mjzRLMaASed9a1tKJdIWkmdiVxY1Wf/Oy2xbjl6xbPeNVBf1vdP80gSDt6oJC7eOyFUkjHW8RP/7Cx_sk
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer1.talentsprint/peers/peer1.mypeer1.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer1.talentsprint/peers/peer1.mypeer1.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer1.mypeer1.talentsprint:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - byfn

  peer2.mypeer1.talentsprint:
    container_name: peer2.mypeer1.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.mypeer1.talentsprint
      - CORE_PEER_ADDRESS=peer2.mypeer1.talentsprint:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer2.mypeer1.talentsprint:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1. .talentsprint:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.mypeer1.talentsprint:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
     # - FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgZ+60xQvTq/z6F/ZbQrFdf52ALHHJ2U9z/ixk2wENH3ShRANCAARLHHokC1mjzRLMaASed9a1tKJdIWkmdiVxY1Wf/Oy2xbjl6xbPeNVBf1vdP80gSDt6oJC7eOyFUkjHW8RP/7Cx_sk
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer1.talentsprint/peers/peer2.mypeer1.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer1.talentsprint/peers/peer2.mypeer1.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer2.mypeer1.talentsprint:/var/hyperledger/production
    ports:
      - 8051:8051
    networks:
      - byfn

  peer1.mypeer2.talentsprint:
    container_name: peer1.mypeer2.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mypeer2.talentsprint
      - CORE_PEER_ADDRESS=peer1.mypeer2.talentsprint:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer1.mypeer2.talentsprint:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.mypeer2.talentsprint:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mypeer2.talentsprint:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    # - FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgbM4we9AUPQYRtNWUeHJyruyPQ3tYbCANqVl+3gVnrxmhRANCAAQleYcECttVsgtueGsduEq4kZYi3OqPmDb1YGeebpS5TKab28s5kp4bsZ56/6dfo48xyA+r59imZ+Cg1c6kjbuB_sk

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer2.talentsprint/peers/peer1.mypeer2.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer2.talentsprint/peers/peer1.mypeer2.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer1.mypeer2.talentsprint:/var/hyperledger/production
    ports:
      - 9051:9051
    networks:
      - byfn

  peer2.mypeer2.talentsprint:
    container_name: peer2.mypeer2.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.mypeer2.talentsprint
      - CORE_PEER_ADDRESS=peer2.mypeer2.talentsprint:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer2.mypeer2.talentsprint:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.mypeer2.talentsprint:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.mypeer2.talentsprint:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
      # -FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgbM4we9AUPQYRtNWUeHJyruyPQ3tYbCANqVl+3gVnrxmhRANCAAQleYcECttVsgtueGsduEq4kZYi3OqPmDb1YGeebpS5TKab28s5kp4bsZ56/6dfo48xyA+r59imZ+Cg1c6kjbuB_sk
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer2.talentsprint/peers/peer2.mypeer2.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer2.talentsprint/peers/peer2.mypeer2.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer2.mypeer2.talentsprint:/var/hyperledger/production
    ports:
      - 10051:10051
    networks:
      - byfn

  peer1.mypeer3.talentsprint:
    container_name: peer1.mypeer3.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mypeer3.talentsprint
      - CORE_PEER_ADDRESS=peer1.mypeer3.talentsprint:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer1.mypeer3.talentsprint:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.mypeer3.talentsprint:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mypeer3.talentsprint:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
    #  - FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg+a2TrePaoe23eE/9PflbQMB9acCXgSbHLJOqaxoxGSyhRANCAAQllm6tCl7QFpeB8sww+YO0NYpDyFmdFD9q2UdxJIW6/rVTfLyThGLOu8rjQifh8ouPEBR/3LTraRxjygyze2SR_sk
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer3.talentsprint/peers/peer1.mypeer3.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer3.talentsprint/peers/peer1.mypeer3.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer1.mypeer3.talentsprint:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - byfn

  peer2.mypeer3.talentsprint:
    container_name: peer2.mypeer3.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.mypeer3.talentsprint
      - CORE_PEER_ADDRESS=peer2.mypeer3.talentsprint:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer2.mypeer3.talentsprint:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.mypeer3.talentsprint:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.mypeer3.talentsprint:12051
      - CORE_PEER_LOCALMSPID=Org3MSP
    #  - FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg+a2TrePaoe23eE/9PflbQMB9acCXgSbHLJOqaxoxGSyhRANCAAQllm6tCl7QFpeB8sww+YO0NYpDyFmdFD9q2UdxJIW6/rVTfLyThGLOu8rjQifh8ouPEBR/3LTraRxjygyze2SR_sk
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer3.talentsprint/peers/peer2.mypeer3.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer3.talentsprint/peers/peer2.mypeer3.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer2.mypeer3.talentsprint:/var/hyperledger/production
    ports:
      - 12051:12051
    networks:
      - byfn

  peer1.mypeer4.talentsprint:
    container_name: peer1.mypeer4.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mypeer4.talentsprint
      - CORE_PEER_ADDRESS=peer1.mypeer4.talentsprint:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer1.mypeer4.talentsprint:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.mypeer4.talentsprint:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mypeer4.talentsprint:13051
      - CORE_PEER_LOCALMSPID=Org4MSP
   #   - FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgt5C0p9ZB/pNbLLUEhcNTy6u32rrp3SRh4hQJ4zNfcduhRANCAAT62JqaoIFcxiyT0/LklUKmv3EH/p28cGKC2oruK2xFVd8EZkQ6qqP9rXGrjhdI8CTP5CjzrCH82b66zTN3+hRh_sk
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer4.talentsprint/peers/peer1.mypeer4.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer4.talentsprint/peers/peer1.mypeer4.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer1.mypeer4.talentsprint:/var/hyperledger/production
    ports:
      - 13051:13051
    networks:
      - byfn

  peer2.mypeer4.talentsprint:
    container_name: peer2.mypeer4.talentsprint
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.mypeer4.talentsprint
      - CORE_PEER_ADDRESS=peer2.mypeer4.talentsprint:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer2.mypeer4.talentsprint:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.mypeer4.talentsprint:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.mypeer4.talentsprint:14051
      - CORE_PEER_LOCALMSPID=Org4MSP
     # - FABRIC_CA_SERVER_TLS_KEYFILE=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgt5C0p9ZB/pNbLLUEhcNTy6u32rrp3SRh4hQJ4zNfcduhRANCAAT62JqaoIFcxiyT0/LklUKmv3EH/p28cGKC2oruK2xFVd8EZkQ6qqP9rXGrjhdI8CTP5CjzrCH82b66zTN3+hRh_sk
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mypeer4.talentsprint/peers/peer2.mypeer4.talentsprint/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mypeer4.talentsprint/peers/peer2.mypeer4.talentsprint/tls:/etc/hyperledger/fabric/tls
        - peer2.mypeer4.talentsprint:/var/hyperledger/production
    ports:
      - 14051:14051
    networks:
      - byfn


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.mypeer1.talentsprint:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mypeer1.talentsprint/peers/peer1.mypeer1.talentsprint/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mypeer1.talentsprint/peers/peer1.mypeer1.talentsprint/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mypeer1.talentsprint/peers/peer1.mypeer1.talentsprint/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mypeer1.talentsprint/users/Admin@mypeer1.talentsprint/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./myscripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/myscripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.talentsprint
      - orderer2.talentsprint
      - orderer3.talentsprint
      - orderer4.talentsprint
      - orderer5.talentsprint
      - peer1.mypeer1.talentsprint
      - peer2.mypeer1.talentsprint
      - peer1.mypeer2.talentsprint
      - peer2.mypeer2.talentsprint
      - peer1.mypeer3.talentsprint
      - peer2.mypeer3.talentsprint
      - peer1.mypeer4.talentsprint
      - peer2.mypeer4.talentsprint
    networks:
      - byfn
